# Generated by Django 2.2.2 on 2019-06-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='print',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
