# Generated by Django 2.2.1 on 2019-06-13 14:35

import boards.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20190613_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=boards.models.board_image_path),
        ),
    ]
